#!/bin/bash

ARRAY=(${QUERY_STRING//[=&&]/ })

while true; do
    mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /[0-9]/ {print $3}' > .tmp_cpu
    line_count=$(wc -l .tmp_cpu | awk '{ print $1 }')
    output="$line_count"
    counter=1

    while read line; do
        output="$output C$counter $line"
        counter=`expr $counter + 1`
    done < .tmp_cpu
    echo $output

	sleep ${ARRAY[1]:=0.3}
done
