#!/bin/bash

ARRAY=(${QUERY_STRING//[=&&]/ })

while true; do
	A=$((40 + $RANDOM % 4))
	B=$((50 + $RANDOM % 4))
	C=$((30 + $RANDOM % 5))
	D=$((35 + $RANDOM % 5))
	E=$((30 + $RANDOM % 10))
	F=$((85 + $RANDOM % 15))
	G=$((75 + $RANDOM % 10))
	echo $A $B $C $D $E $F $G
	sleep ${ARRAY[1]:=0.3}
done
